website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from firebase_admin import credentials
from firebase_admin import firestore
from .functions import *

#Firebase Auth Kurulumu
auth = Blueprint('auth', __name__)


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if(authFirebase.current_user):
            return redirect(url_for('views.home'))
    
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password = request.form.get('password')
        ilgi_Alani = request.form.get('ilgiAlani')
        ilgi_AlaniArray = ilgi_Alani.split(",")

        
        ilgiSciVector, ilgiFTVector = vectorGettingilgi(ilgi_AlaniArray)
        ilgiSciVectorA = ilgiSciVector.tolist()
        ilgiFTVectorA = ilgiFTVector.tolist()

        userData = {
        'email' : email,
        'first_name' : first_name,
        'ilgi_Alani' : ilgi_AlaniArray,
        'ilgiSciVectorA':ilgiSciVectorA,
        'ilgiFTVectorA':ilgiFTVectorA
        }

        try:
            user = authFirebase.create_user_with_email_and_password(email,password)
            authFirebase.current_user = user
            db.collection('Users').document(f"{email}").set(userData)
            return redirect(url_for('views.home'))
        except:
            return render_template("sign_up.html")
        
    return render_template("sign_up.html")
        
@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        

        try:
            user = authFirebase.sign_in_with_email_and_password(email,password)
            authFirebase.current_user = user

            
            return redirect(url_for('views.home'))
            
        except:
            return redirect(url_for('auth.login'))   

    return render_template("login.html")

@auth.route('/logout')
def logout():
    try:
        authFirebase.current_user = None
    except:
        redirect(url_for('auth.login'))
    return redirect(url_for('auth.login'))



website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from .auth import *
from .functions import *

#internet sitesi routing işlemlerinin olduğu yer.

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    
    if(authFirebase.current_user):
        try:
            user = db.collection('Users').document(authFirebase.current_user['email']).get()
            user = user.to_dict()
          
        except:
            return "<h1>Kullanici Bilgisi Cekilemedi</h1>"
        return render_template("home.html",currentuser = authFirebase.current_user,user = user)
    else:
        return redirect(url_for('auth.login'))

@views.route('/search/<emailAdress>',methods=['GET', 'POST'])
def search(emailAdress):

    if(authFirebase.current_user):
        
        try:
            user = db.collection('Users').document(emailAdress).get()
            user = user.to_dict()
          
        except:
            return "<h1>Kullanici Bilgisi Cekilemedi</h1>"
        
        
        if request.method == 'POST':
            arananKelime = request.form.get('aramaCubugu')

            try:
                docs = db.collection('Assays').where("keyWords", "array_contains", arananKelime).get()
                aratilmisDocs = []

                for doc in docs:
                    doc = doc.to_dict()
                    aratilmisDocs.append(doc)
                

            except:
                aratilmisDocs = []

            return render_template("search.html",currentuser = authFirebase.current_user,aratilmisDocs = aratilmisDocs)


        pass

    else:
        return redirect(url_for('auth.login'))
@views.route('/searchedAssay/<emailAdress>/<id>',methods=['GET', 'POST'])
def searchedAssay(emailAdress,id):

    if(authFirebase.current_user):
        try:
            user = db.collection('Users').document(emailAdress).get()
            user = user.to_dict()
            doc = db.collection('Assays').document(id).get()
            doc = doc.to_dict()
          
        except:
            return "<h1>Kullanici Bilgisi Cekilemedi</h1>"
        
        if request.method == 'POST':
            sci = user['ilgiSciVectorA']
            ft = user['ilgiFTVectorA']
            sci = np.array(sci)
            ft = np.array(ft)
            
            
            docSciVector = doc['sciVectorA']
            docSciVector = np.array(docSciVector)
            docFtVector = doc['ftVectorA']
            docFtVector = np.array(docFtVector)

            newVectorSci = (sci + docSciVector) / 2 
            newVectorFt = (ft + docFtVector) / 2

            newVectorSci = newVectorSci.tolist()
            newVectorFt = newVectorFt.tolist()

            vectorData = {
                'ilgiSciVectorA':newVectorSci,
                'ilgiFTVectorA': newVectorFt
            }

            try:
                db.collection('Users').document(emailAdress).update(vectorData)
            except:
                return "<h1>Guncellenemedi</h1>"

        return render_template("searchedAssay.html",currentuser = authFirebase.current_user,doc = doc)
    else:
        return redirect(url_for('auth.login'))

@views.route('/profile/<emailAdress>',methods=['GET', 'POST'])
def profile(emailAdress):

    if(authFirebase.current_user):
        
        try:
            user = db.collection('Users').document(emailAdress).get()
            user = user.to_dict()
          
        except:
            return "<h1>Kullanici Bilgisi Cekilemedi</h1>"
        
        if request.method == 'POST':
            currentUser = authFirebase.current_user
            first_name = request.form.get('firstName')
            ilgi_Alani = request.form.get('ilgiAlani')
            if not (ilgi_Alani or first_name):
                return render_template("profile.html",currentuser = authFirebase.current_user,user = user)
            
            ilgi_AlaniArray = str(ilgi_Alani).split(",")
            ilgiSciVector, ilgiFTVector = vectorGettingilgi(ilgi_AlaniArray)
            ilgiSciVectorA = ilgiSciVector.tolist()
            ilgiFTVectorA = ilgiFTVector.tolist()

            data = {
                    'email' : emailAdress,
                    'first_name' : first_name,
                    'ilgi_Alani' : ilgi_AlaniArray,
                    'ilgiSciVectorA':ilgiSciVectorA,
                    'ilgiFTVectorA':ilgiFTVectorA           
                }
            try:
                db.collection('Users').document(emailAdress).update(data)
                return redirect(url_for('views.home'))
            except:
                return "<h1>Guncellenemedi</h1>"
                
        return render_template("profile.html",currentuser = authFirebase.current_user,user = user)
    else:
        return redirect(url_for('auth.login'))
    
@views.route('/recommends/<emailAdress>',methods=['GET', 'POST'])
def recommends(emailAdress):
    if(authFirebase.current_user):
        
        try:
            
            user = db.collection('Users').document(emailAdress).get()
            user = user.to_dict()
          
        except:
            return "<h1>Kullanici Bilgisi Cekilemedi</h1>"
        
        sci = user['ilgiSciVectorA']
        ft = user['ilgiFTVectorA']
        sci = np.array(sci)
        ft = np.array(ft)
        en_benzer_besSci,en_benzer_besFt = similartyIlgiVector(sci,ft)

        sciDocsArray = []
        ftDocsArray = []
        for sciDocs in en_benzer_besSci:
            sciDoc = db.collection('Assays').document(sciDocs['id']).get()
            sciDoc = sciDoc.to_dict()
            sciDocsArray.append(sciDoc)
        
        for ftDocs in en_benzer_besFt:
            ftDoc = db.collection('Assays').document(ftDocs['id']).get()
            ftDoc = ftDoc.to_dict()
            ftDocsArray.append(ftDoc)


        if request.method == 'POST':
            listSci = []
            listFt = []
            
            for key in request.form.keys():
                value = request.form.get(key)
                if value:

                    checkBoxDoc = db.collection('Assays').document(key).get()
                    checkBoxDoc = checkBoxDoc.to_dict()
                    checkBoxDocSci = checkBoxDoc['sciVectorA']
                    checkBoxDocFt = checkBoxDoc['ftVectorA']
                
                    checkBoxDocSci = np.array(checkBoxDocSci)
                    checkBoxDocFt = np.array(checkBoxDocFt)
                    listSci.append(checkBoxDocSci)
                    listFt.append(checkBoxDocFt)
                else:
                    checkBoxDoc = db.collection('Assays').document(key).get()
                    checkBoxDoc = checkBoxDoc.to_dict()
                    checkBoxDocSci = checkBoxDoc['sciVectorA']
                    checkBoxDocFt = checkBoxDoc['ftVectorA']
                
                    checkBoxDocSci = np.array(checkBoxDocSci)
                    checkBoxDocFt = np.array(checkBoxDocFt)
                    checkBoxDocSci = checkBoxDocSci * -1
                    checkBoxDocFt = checkBoxDocFt * -1
                    listSci.append(checkBoxDocSci)
                    listFt.append(checkBoxDocFt)

            listSci.append(sci)
            listFt.append(ft)

            newSciVector = np.mean(listSci,axis=0)
            newFtVector = np.mean(listFt,axis=0)
            newSciVector = newSciVector.tolist()
            newFtVector = newFtVector.tolist()

            vectorData = {
                'ilgiSciVectorA':newSciVector,
                'ilgiFTVectorA': newFtVector
            }

            try:
                db.collection('Users').document(emailAdress).update(vectorData)
                return redirect(url_for('views.home'))
            except:
                return "<h1>Guncellenemedi</h1>"

        return render_template("recommends.html",sciDocsArray = sciDocsArray,ftDocsArray=ftDocsArray,currentuser = authFirebase.current_user,benzerliklerSci = en_benzer_besSci,benzerliklerFt = en_benzer_besFt)
    else:
        return redirect(url_for('auth.login'))




website/templates/home.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
        />
     <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
      />

      <style>
        .home{
    
        }
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }
        }
         .homeButton{
          width = 200px;
          height: 100px;
        }
        .buttonsHome{
          
          display: flex;
          flex-direction: row;
          width: 400px;
          margin-inline: auto;
          border: 3px solid #51adc2;
          justify-content: space-between;
          background-color: #51adc2;

          
        }
        .aramaCubugu{
          width: 322px;
        }
      </style>
    
    </head>
    <body>
      <div class = "home">
       <h3 align="center">Merhabalar Sayin {{user['first_name']}}</h3> <br>
       <div class = "buttonsHome">
       <form method="POST" action ="{{url_for('views.search', emailAdress = currentuser['email'])}}" >
          <input class = "aramaCubugu" type="text" name="aramaCubugu" placeholder = "Bir arama yap." />
          <input type="submit" value="Gönder" />
        </form>
        </div>

        <div class = "buttonsHome">
        <form action ="{{url_for('auth.logout')}}" >
          <input
          type = "submit"
          value = "Cikis"
          class = "homeButton"
          />
        </form>
        <form action ="{{url_for('views.profile', emailAdress = currentuser['email'])}}" >
          <input
          type = "submit"
          value = "Profil"
          class = "homeButton"
          />
        </form>
        <form action ="{{url_for('views.recommends', emailAdress = currentuser['email'])}}" >
          <input
          type = "submit"
          value = "Öneriler"
          class = "homeButton"
          />
        </form>
        </div>
        <script src="" async defer></script>
      </div>
    </body>
</html>

website/templates/login.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />

      <style>
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }
      </style>

    </head>
    <body>
       <form method="POST">
  <h3 align="center">Giris</h3>
  <div class="form-group">
    <label for="email">Email Adresi</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Sifre</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Sifrenizi Giriniz"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Giris Yap</button>
</form>
    <button type="submit" onclick="location.href='/sign-up';" class="btn btn-primary">Kayit</button>
        <script src="" async defer></script>
    </body>
</html>

website/templates/profile.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
      <style>
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccffcc 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }
      </style>
    </head>
    <body>
<h3 align="center">Bilgiler</h3>
<div>
    <p>Email : {{user['email']}}</p>
    <p>İsim : {{user['first_name']}}</p>
    <p>Ilgi Alanlari : {{user['ilgi_Alani']}}</p>
</div>

<form method='POST'>
  <h3 align="center">Bilgi Değiştirmek Icin</h3>
  <div class="form-group">
    <label for="firstName">İsim</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="İsim giriniz"
    />
  </div>
   <div class="form-group">
    <label for="ilgiAlani">ilgi Alani</label>
    <input
      type="text"
      class="form-control"
      id="ilgiAlani"
      name="ilgiAlani"
      placeholder="Düzenlemek için ilgi alanlari giriniz, Lütfen ',' ile ayirin."
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Degistir</button>
</form>
    <div>
    <form action ="{{url_for('views.home')}}" >
          <input
          type = "submit"
          value = "Ana Sayfa"
          />
    </form>
    </div>
    
    </body>
</html>

website/templates/recommends.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <style>
        .öneriDiv{
             
        }  
        .geriBildirim{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
        }

        
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }
        
        </style>
    </head>
    <body>
    
  <h3 align="center">SciBERT Öneriler</h3>
  <div> 
    {%for sciDoc in sciDocsArray%}
        
            <div class ="öneriDiv">
                <h5 align="center">{{sciDoc['title']}}</h5>

                <p>{{sciDoc['document']}}</p>
            </div>
        
    {%endfor%}
  </div>
  <h3 align="center">FastText Öneriler</h3>
  <div> 
    {%for ftDoc in ftDocsArray%}
        
            <div class ="öneriDiv">
                <h5 align="center">{{ftDoc['title']}}</h3>

                <p>{{ftDoc['document']}}</p>
            </div>
        
    {%endfor%}
  </div>
<div>
<form method="POST">
  <div class = "geriBildirim">
  <div style="margin:10px">
  <h4 align=>Geri Bildirim SciBERT</h3>
    {%for sciDoc in sciDocsArray%}
  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" name={{sciDoc['id']}}>
  <label class="form-check-label" for="flexCheckDefault">
    {{sciDoc['title']}} makalesini beğendim
  </label>
    </div>
    {%endfor%}
    </div>
    <div style="margin:10px">
    <h4 align=>Geri Bildirim FastText</h3>
    {%for ftDoc in ftDocsArray%}
  <div class="form-check">
  <input class="form-check-input" type="checkbox" value="" name={{ftDoc['id']}}>
  <label class="form-check-label" for="flexCheckDefault">
    {{ftDoc['title']}} makalesini beğendim
  </label>
    </div>
    {%endfor%}
    </div>
  <br />
  <button type="submit" class="btn btn-primary">Geri Bildir</button>
</form>

</div>


    <div>
    <form action ="{{url_for('views.home')}}" >
          <input
          type = "submit"
          value = "Ana Sayfa"
          />
    </form>
    </div>

    </body>
</html>

website/templates/search.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <style>
        .öneriDiv{
            background-color: #33ccff;
            border 2px solid #dcf0d3; 
        }
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }  
        .aramaSonuclari{
            display: flex;
            flex-direction: column;
        }
        .aramaForm{
            width: 100%;
            
        }   
        </style>
    </head>




    <body>
    
  <h3 align="center">Arama sonuçlari</h3>
  <div class = "aramaSonuclari"> 
    {%for doc in aratilmisDocs%}
        
        <div class ="öneriDiv">
            <h4 align="center">{{doc['title']}}</h4>
            <form method = "POST" action ="{{url_for('views.searchedAssay',emailAdress = currentuser['email'],id = doc['id'])}}" >
            <input
            type = "submit"
            value = "Okumak için tiklayin."
            class = "aramaForm"
            />
            </form>
        </div>
        
    {%endfor%}
  </div>

    <div>
    <form action ="{{url_for('views.home')}}" >
          <input
          type = "submit"
          value = "Ana Sayfa"

          />
    </form>
    </div>
    </body>
</html>

website/templates/searchedAssay.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <style>
        .makale{
            
            display: flex;
            flex-direction: column; 
        }
        .keywords{
            display: flex;
            flex-direction: row;
            
        }
        .key{
            margin-left: 10px;
        }
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }  
        </style>
    </head>

    <body>
    
  
  <div class = "makale">
  <h1 align="center">{{doc['title']}}</h1> 
    <div class = "document">
    <h4>Makale Özeti</h4>
        <p>{{doc['document']}}</p>
    </div>
    <div class ="keywords">
        <p>Anahtar Kelimeler : </p>

         {%for key in doc['keyWords']%} <div class = "key"> <p>"{{key}}"</p> </div> {%endfor%}

    </div>
  </div>

    <div>
    <form action ="{{url_for('views.home')}}" >
          <input
          type = "submit"
          value = "Ana Sayfa"

          />
    </form>
    </div>
    </body>
</html>

website/templates/sign_up.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />
        <style>
        body {
        background: linear-gradient(to bottom, #33ccff 0%, #ccff99 100%);
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        background-position: center;
         }
      </style>
    </head>
    <body>

    
    

        <form method="POST">
  <h3 align="center">Kayit Ol</h3>
  <div class="form-group">
    <label for="email">Email Adresi</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Email Giriniz"
    />
  </div>
  <div class="form-group">
    <label for="firstName">İsim</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="İsim Giriniz"
    />
  </div>
  <div class="form-group">
    <label for="password">Sifre</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Sifre Giriniz"
    />
  </div>
   <div class="form-group">
    <label for="ilgiAlani">ilgi Alani</label>
    <input
      type="text"
      class="form-control"
      id="ilgiAlani"
      name="ilgiAlani"
      placeholder="ilgi Alani Giriniz Virgül ile"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Kayit Ol</button>
</form>
<button type="submit" onclick="location.href='/login';" class="btn btn-primary">Giris</button>
        <script src="" async defer></script>
    </body>
</html>